print "Hello World"
print "First Program of Python"
print "Pretty straight forward i guess"
print "No need to worry i guess for now at least"
print "No need of any Expectations in beginning"
print "Pretty happy"